var ilce: String = "Ataköy"
var kita: String = "Asya"
var faks: String = "0216 123 4567"
var postaKodu: Int = 34740
var instaAdresi: String = "@eminmemioglu"
var calistiginBolum: String = "IOS"
var urunMiktari: Int = 50
var musteriSoyadi: String = "memioğlu"
var odemeMiktari: Double = 1289.50
var dogumTarihi: String = "24.09.2004"
var borc: Double = 350.75
var medeniHal: Bool = false
var videoYorumu: Bool = true
var odemeSaati: String = "14:30"
var eftMiktari: Double = 500.00
var satilanMiktar: Int = 20
var telefonModeli: String = "iPhone 14"
var dergiAdi: String = "Bilim Teknik"
var basimTarihi: String = "15.09.2004"
var zamMiktari: Double = 200.00
var daireSayisi: Int = 10
var enlem: Double = 41.0082
var boylam: Double = 28.9784
var yemekAdi: String = "Pizza"
var urunFiyati: Double = 99.99
var sirket: String = "BTK Yazılım"
var videoAdi: String = "İOS BOOTCAMP"
var muzikSuresi: Double = 3.45
var mekanPuani: Double = 4.8
var dosyaAdi: String = "bootcamp.pdf"
var resimFormati: String = ".jpeg"
var renk: String = "Mavi"
var bilgisayarModeli: String = "MacBook Pro"
var ekranBoyutu: Double = 13.3
var kullanimSuresi: Int = 365
var basinc: Double = 1013.25
var etkinlikGunu: String = "15.09.2004"
var odemeGunu: String = "15.09.2004"
var yolculukCikisTarihi: String = "15.09.2004"
var mahalleAdi: String = "Mecidiyeköy"
var otobusHatti: String = "15TA"
var kullanilanDakika: Int = 500
var kargoTakipNo: Int = 123456789
var kuponSuresi: Int = 30
var kuponKodu: String = "INDIRIM50"
var faturaTarihi: String = "15.09.2004"
